# # This is a basic workflow to help you get started with Actions

# # This is what is called
# name: Node JS Testing 

# # is activated when a new commit is made or on main 
# on:
#   push:
#     branches: [ "new commit" ]
#   pull_request:
#     branches: [ "main" ]
#   # allows you to manually trigger a workflow from the GitHub Actions tab in the GitHub web interface
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest 

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v4

#       - uses: actions/checkout@v4
#         with: 
#           node-version: '20'

#       - run: npm install 

#       - run: npm test 
#         env: 
#           API_KEY: ${{ secrets.API_KEY }}




# by Parsa 

name: Node.js Package 

on: 
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - main 

jobs:
  build: 
    runs-on: ubantu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4 

      - name: Set up Node.js
        uses: actions/setup-node@v4 
        with: 
          node-version: 20

      - name: Install dependencies 
        run: npm install 

      - name: Run tests 
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
          # Name/Value is pulled from Github > Settings > Secrets and Variables > Actions > New repo secret 
        run: npm test 
  
